manifest:
  version: "0.13"
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect/sdk-nrf
  projects:
    - name: nrf
      remote: ncs
      revision: main
      path: ncs
      import: true
